// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBybeDfszJ06hzxDugJ3Se-Em7VOx5I39Y',
    appId: '1:918421407018:web:2b5a6f18852b258381ca53',
    messagingSenderId: '918421407018',
    projectId: 'recipes-7d99a',
    authDomain: 'recipes-7d99a.firebaseapp.com',
    storageBucket: 'recipes-7d99a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6LD4PDuYAB_scZRhFvqtOFpU_Kc0chVA',
    appId: '1:918421407018:android:2d800c872756f1e381ca53',
    messagingSenderId: '918421407018',
    projectId: 'recipes-7d99a',
    storageBucket: 'recipes-7d99a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAr0Mf8xFfn43ZV0QORDD94jiKpUt38JV4',
    appId: '1:918421407018:ios:0880197557120f5a81ca53',
    messagingSenderId: '918421407018',
    projectId: 'recipes-7d99a',
    storageBucket: 'recipes-7d99a.appspot.com',
    iosBundleId: 'com.example.recipes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAr0Mf8xFfn43ZV0QORDD94jiKpUt38JV4',
    appId: '1:918421407018:ios:bfb17f07c294dc4981ca53',
    messagingSenderId: '918421407018',
    projectId: 'recipes-7d99a',
    storageBucket: 'recipes-7d99a.appspot.com',
    iosBundleId: 'com.example.recipes.RunnerTests',
  );
}
